import { afterEach, describe, expect, it, vi } from "@effect/vitest";
import { ConfigProvider, Effect, Either, Layer } from "effect";
import {
  GitHubAppApiError,
  GitHubAppConfigurationError,
  GitHubAppRemoteError,
} from "../src/domain/errors.js";
import { GatewayConfig } from "../src/services/config.js";
import { GitHubApp, parseGitHubRemote } from "../src/services/github-app.js";

const baseValues = new Map<string, string>([
  ["LINEAR_CLIENT_ID", "client"],
  ["LINEAR_CLIENT_SECRET", "secret"],
  ["LINEAR_ALLOWED_ORGANIZATION_IDS", "test-org"],
  ["LINEAR_WEBHOOK_SECRET", "webhook"],
  [
    "TOKEN_ENCRYPTION_KEY",
    Buffer.from(new Uint8Array(32).fill(4)).toString("base64"),
  ],
  ["PUBLIC_URL", "https://ohmypi-symphony.ai.roxasroot.net"],
]);

const service = (values: Map<string, string>) =>
  GitHubApp.Default.pipe(
    Layer.provide(
      GatewayConfig.Default.pipe(
        Layer.provide(Layer.setConfigProvider(ConfigProvider.fromMap(values))),
      ),
    ),
  );

const createInput = {
  repositoryUrl: "git@github.com:octo/example.git",
  base: "main",
  head: "feature/example",
  title: "Open a pull request",
  body: "Generated by the gateway",
} as const;

const publishInput = {
  repositoryUrl: "git@github.com:octo/example.git",
  base: "main",
  branch: "gateway/00000000000000000000000000000000",
  workspacePath: "/workspace",
  title: "Open a pull request",
  body: "Generated by the gateway",
} as const;

const configuredApp = async () => {
  const values = new Map(baseValues);
  values.set("GITHUB_APP_ID", "123");
  values.set("GITHUB_APP_PRIVATE_KEY", await pemPrivateKey());
  return Effect.runPromise(
    Effect.gen(function* () {
      return yield* GitHubApp;
    }).pipe(Effect.provide(service(values))),
  );
};

const pemPrivateKey = async (): Promise<string> => {
  const pair = await crypto.subtle.generateKey(
    {
      name: "RSASSA-PKCS1-v1_5",
      modulusLength: 1024,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["sign", "verify"],
  );
  const bytes = new Uint8Array(
    await crypto.subtle.exportKey("pkcs8", pair.privateKey),
  );
  const encoded = Buffer.from(bytes).toString("base64");
  return `-----BEGIN PRIVATE KEY-----\n${encoded.match(/.{1,64}/g)?.join("\n")}\n-----END PRIVATE KEY-----`;
};

interface GitStep {
  readonly exitCode?: number;
  readonly stdout?: string;
  readonly stderr?: string;
}

const stubGit = (steps: ReadonlyArray<GitStep>) => {
  const remaining = [...steps];
  const commands: string[][] = [];
  const spawnImplementation = (command: Parameters<typeof Bun.spawn>[0]) => {
    if (!Array.isArray(command)) throw new Error("unexpected spawn command");
    commands.push(command.map((part) => String(part)));
    const step = remaining.shift() ?? {};
    const stdout = new Response(step.stdout ?? "").body;
    const stderr = new Response(step.stderr ?? "").body;
    return {
      exited: Promise.resolve(step.exitCode ?? 0),
      stdout,
      stderr,
    } as never;
  };
  const spawn = vi.spyOn(Bun, "spawn").mockImplementation(spawnImplementation);
  return { commands, spawn };
};

afterEach(() => {
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("GitHubApp", () => {
  it("stays disabled when the grouped configuration is absent", async () => {
    const app = await Effect.runPromise(
      Effect.gen(function* () {
        return yield* GitHubApp;
      }).pipe(Effect.provide(service(new Map(baseValues)))),
    );

    expect(app.isEnabled()).toBe(false);
    const result = await Effect.runPromise(
      Effect.either(app.createPullRequest(createInput)),
    );
    expect(Either.isLeft(result)).toBe(true);
    if (Either.isLeft(result)) {
      if (result.left instanceof GitHubAppConfigurationError) {
        expect(result.left.missing).toEqual([
          "GITHUB_APP_ID",
          "GITHUB_APP_PRIVATE_KEY",
        ]);
      } else {
        throw new Error("unexpected GitHub App error");
      }
    }
  });
  it("does not inspect or publish a workspace when disabled", async () => {
    const app = await Effect.runPromise(
      Effect.gen(function* () {
        return yield* GitHubApp;
      }).pipe(Effect.provide(service(new Map(baseValues)))),
    );
    const result = await Effect.runPromise(
      app.publishPullRequest({
        repositoryUrl: "https://github.com/octo/example.git",
        base: "main",
        branch: "gateway/00000000000000000000000000000000",
        workspacePath: "/path-that-must-not-be-read",
        title: "unused",
        body: "unused",
      }),
    );
    expect(result).toBeUndefined();
  });

  it("accepts canonical HTTPS and SSH remotes and rejects other hosts", () => {
    expect(parseGitHubRemote("https://github.com/octo/example.git")).toEqual({
      owner: "octo",
      repository: "example",
    });
    expect(parseGitHubRemote("git@github.com:octo/example.git")).toEqual({
      owner: "octo",
      repository: "example",
    });
    expect(() =>
      parseGitHubRemote("https://github.example.com/octo/example"),
    ).toThrow(GitHubAppRemoteError);
    expect(() =>
      parseGitHubRemote("https://github.com/octo/example/issues"),
    ).toThrow(GitHubAppRemoteError);
  });

  it("defers partially configured errors until PR creation", async () => {
    const values = new Map(baseValues);
    values.set("GITHUB_APP_ID", "123");
    const app = await Effect.runPromise(
      Effect.gen(function* () {
        return yield* GitHubApp;
      }).pipe(Effect.provide(service(values))),
    );

    expect(app.isEnabled()).toBe(true);
    const result = await Effect.runPromise(
      Effect.either(app.createPullRequest(createInput)),
    );
    expect(Either.isLeft(result)).toBe(true);
    if (Either.isLeft(result)) {
      if (result.left instanceof GitHubAppConfigurationError) {
        expect(result.left.missing).toEqual(["GITHUB_APP_PRIVATE_KEY"]);
      } else {
        throw new Error("unexpected GitHub App error");
      }
    }
  });

  it("returns no PR and skips token exchange for a clean workspace at its base", async () => {
    const app = await configuredApp();
    const { commands } = stubGit([{ stdout: "" }, { stdout: "0\n" }]);
    const fetchMock = vi.fn<typeof fetch>();
    vi.stubGlobal("fetch", fetchMock);

    const result = await Effect.runPromise(
      app.publishPullRequest(publishInput),
    );
    expect(result).toBeUndefined();
    expect(commands.map((command) => command.slice(1))).toEqual([
      ["status", "--porcelain"],
      ["rev-list", "--count", "FETCH_HEAD..HEAD"],
    ]);
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it("commits residual work with gateway identity before pushing", async () => {
    const app = await configuredApp();
    const { commands } = stubGit([
      { stdout: " M file.txt\n" },
      { stdout: "0\n" },
      {},
      { exitCode: 1 },
      {},
      { stdout: "1\n" },
      {},
    ]);
    const fetchMock = vi
      .fn<typeof fetch>()
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ id: 456 }), { status: 200 }),
      )
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ token: "installation-secret" }), {
          status: 201,
        }),
      )
      .mockResolvedValueOnce(new Response(JSON.stringify([]), { status: 200 }))
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            html_url: "https://github.com/octo/example/pull/9",
            number: 9,
          }),
          { status: 201 },
        ),
      );
    vi.stubGlobal("fetch", fetchMock);

    const result = await Effect.runPromise(
      app.publishPullRequest(publishInput),
    );
    expect(result).toEqual({
      url: "https://github.com/octo/example/pull/9",
      number: 9,
    });
    const commit = commands.find((command) => command.includes("commit"));
    expect(commit).toEqual([
      "git",
      "-c",
      "user.name=OhMyPi Gateway",
      "-c",
      "user.email=ohmypi-gateway@localhost",
      "commit",
      "-m",
      "Gateway workspace changes",
    ]);
    expect(commit).not.toContain("--no-verify");
  });

  it("pushes an existing agent commit and reuses an open pull request", async () => {
    const app = await configuredApp();
    stubGit([{ stdout: "" }, { stdout: "1\n" }, {}]);
    const fetchMock = vi
      .fn<typeof fetch>()
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ id: 456 }), { status: 200 }),
      )
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ token: "installation-secret" }), {
          status: 201,
        }),
      )
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify([
            {
              html_url: "https://github.com/octo/example/pull/11",
              number: 11,
            },
          ]),
          { status: 200 },
        ),
      );
    vi.stubGlobal("fetch", fetchMock);

    const result = await Effect.runPromise(
      app.publishPullRequest(publishInput),
    );
    expect(result).toEqual({
      url: "https://github.com/octo/example/pull/11",
      number: 11,
    });
    expect(fetchMock).toHaveBeenCalledTimes(3);
  });

  it("maps git and API publication failures without exposing credentials", async () => {
    const app = await configuredApp();
    stubGit([{ exitCode: 1, stderr: "installation-secret" }]);
    const gitFailure = await Effect.runPromise(
      Effect.either(app.publishPullRequest(publishInput)),
    );
    expect(Either.isLeft(gitFailure)).toBe(true);
    if (Either.isLeft(gitFailure)) {
      expect(gitFailure.left).toBeInstanceOf(GitHubAppApiError);
      expect(gitFailure.left.message).not.toContain("installation-secret");
      expect(gitFailure.left.message).not.toContain("BEGIN PRIVATE KEY");
    }

    const { spawn } = stubGit([{ stdout: "" }, { stdout: "1\n" }, {}]);
    expect(spawn).toBeDefined();
    const fetchMock = vi
      .fn<typeof fetch>()
      .mockResolvedValue(new Response("unauthorized", { status: 401 }));
    vi.stubGlobal("fetch", fetchMock);
    const apiFailure = await Effect.runPromise(
      Effect.either(app.publishPullRequest(publishInput)),
    );
    expect(Either.isLeft(apiFailure)).toBe(true);
    if (Either.isLeft(apiFailure)) {
      expect(apiFailure.left).toBeInstanceOf(GitHubAppApiError);
      expect(apiFailure.left.message).not.toContain("installation-secret");
      expect(apiFailure.left.message).not.toContain("BEGIN PRIVATE KEY");
    }
  });

  it("exchanges an App JWT for an installation token and creates a pull request", async () => {
    const fetchMock = vi.fn<typeof fetch>();
    fetchMock
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ id: 456 }), { status: 200 }),
      )
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ token: "installation-secret" }), {
          status: 201,
        }),
      )
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            html_url: "https://github.com/octo/example/pull/7",
            number: 7,
          }),
          { status: 201 },
        ),
      );
    vi.stubGlobal("fetch", fetchMock);
    const app = await configuredApp();

    const result = await Effect.runPromise(app.createPullRequest(createInput));
    expect(result).toEqual({
      url: "https://github.com/octo/example/pull/7",
      number: 7,
    });
    expect(Object.isFrozen(result)).toBe(true);
    expect(fetchMock).toHaveBeenCalledTimes(3);
    const installationCall = fetchMock.mock.calls[0];
    expect(installationCall?.[0]).toBe(
      "https://api.github.com/repos/octo/example/installation",
    );
    const tokenCall = fetchMock.mock.calls[1];
    expect(tokenCall).toBeDefined();
    if (tokenCall === undefined) throw new Error("missing token request");
    const [tokenUrl, tokenInit] = tokenCall;
    expect(tokenUrl).toBe(
      "https://api.github.com/app/installations/456/access_tokens",
    );
    expect(tokenInit?.method).toBe("POST");
    expect(tokenInit?.headers).toMatchObject({
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    });
    const authorization = new Headers(tokenInit?.headers).get("Authorization");
    if (authorization === null) throw new Error("missing App JWT");
    const jwt = authorization.slice("Bearer ".length);
    const jwtParts = jwt.split(".");
    expect(jwtParts).toHaveLength(3);
    const jwtHeader = jwtParts[0];
    const jwtPayloadEncoded = jwtParts[1];
    if (jwtHeader === undefined || jwtPayloadEncoded === undefined) {
      throw new Error("malformed JWT");
    }
    const decodeJwtPart = (encoded: string) =>
      JSON.parse(
        Buffer.from(
          encoded.replace(/-/g, "+").replace(/_/g, "/"),
          "base64",
        ).toString(),
      ) as Record<string, unknown>;
    const jwtHeaderValue = decodeJwtPart(jwtHeader);
    const jwtPayload = decodeJwtPart(jwtPayloadEncoded) as {
      iss: number;
      iat: number;
      exp: number;
    };
    expect(jwtHeaderValue).toEqual({ alg: "RS256", typ: "JWT" });
    expect(jwtPayload.iss).toBe(123);
    expect(jwtPayload.iat).toBeLessThan(Math.floor(Date.now() / 1000));
    expect(jwtPayload.exp - jwtPayload.iat).toBeLessThanOrEqual(10 * 60);

    const pullCall = fetchMock.mock.calls[2];
    expect(pullCall).toBeDefined();
    if (pullCall === undefined) throw new Error("missing pull request");
    const [pullUrl, pullInit] = pullCall;
    expect(pullUrl).toBe("https://api.github.com/repos/octo/example/pulls");
    expect(pullInit?.headers).toMatchObject({
      Authorization: "Bearer installation-secret",
      "Content-Type": "application/json",
    });
    expect(JSON.parse(String(pullInit?.body))).toEqual({
      title: createInput.title,
      body: createInput.body,
      head: createInput.head,

      base: createInput.base,
    });
  });
  it("rejects an invalid repository installation response safely", async () => {
    const values = new Map(baseValues);
    values.set("GITHUB_APP_ID", "123");
    values.set("GITHUB_APP_PRIVATE_KEY", await pemPrivateKey());
    const fetchMock = vi
      .fn<typeof fetch>()
      .mockResolvedValue(
        new Response(JSON.stringify({ id: "not-a-number" }), { status: 200 }),
      );
    vi.stubGlobal("fetch", fetchMock);
    const app = await Effect.runPromise(
      Effect.gen(function* () {
        return yield* GitHubApp;
      }).pipe(Effect.provide(service(values))),
    );

    const result = await Effect.runPromise(
      Effect.either(app.createPullRequest(createInput)),
    );
    expect(Either.isLeft(result)).toBe(true);
    if (Either.isLeft(result)) {
      expect(result.left.message).toBe(
        "GitHub installation lookup failed for octo/example",
      );
      expect(result.left.message).not.toContain("not-a-number");
      expect(result.left.message).not.toContain("BEGIN PRIVATE KEY");
    }
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });

  it("rejects a missing repository installation before token exchange or push", async () => {
    const app = await configuredApp();
    const { commands } = stubGit([{ stdout: "" }, { stdout: "1\n" }]);
    const fetchMock = vi
      .fn<typeof fetch>()
      .mockResolvedValue(new Response("not found", { status: 404 }));
    vi.stubGlobal("fetch", fetchMock);

    const result = await Effect.runPromise(
      Effect.either(app.publishPullRequest(publishInput)),
    );
    expect(Either.isLeft(result)).toBe(true);
    if (Either.isLeft(result)) {
      expect(result.left).toBeInstanceOf(GitHubAppApiError);
      expect(result.left.message).toBe(
        "GitHub installation lookup failed for octo/example",
      );
    }
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const lookup = fetchMock.mock.calls[0];
    expect(lookup).toBeDefined();
    if (lookup === undefined) throw new Error("missing installation lookup");
    const [lookupUrl, lookupInit] = lookup;
    expect(lookupUrl).toBe(
      "https://api.github.com/repos/octo/example/installation",
    );
    expect(lookupInit?.method).toBeUndefined();
    const authorization = new Headers(lookupInit?.headers).get("Authorization");
    expect(authorization).toMatch(/^Bearer [^.]+\.[^.]+\.[^.]+$/);
    if (authorization === null) throw new Error("missing App JWT");
    const jwtParts = authorization.slice("Bearer ".length).split(".");
    expect(jwtParts).toHaveLength(3);
    if (jwtParts.length !== 3) throw new Error("invalid App JWT");
    const [header, payload] = jwtParts;
    if (header === undefined || payload === undefined) {
      throw new Error("missing App JWT parts");
    }
    expect(
      JSON.parse(
        Buffer.from(
          header.replace(/-/g, "+").replace(/_/g, "/"),
          "base64",
        ).toString(),
      ),
    ).toMatchObject({ alg: "RS256" });
    expect(
      JSON.parse(
        Buffer.from(
          payload.replace(/-/g, "+").replace(/_/g, "/"),
          "base64",
        ).toString(),
      ),
    ).toMatchObject({ iss: 123 });
    expect(commands.map((command) => command.slice(1))).toEqual([
      ["status", "--porcelain"],
      ["rev-list", "--count", "FETCH_HEAD..HEAD"],
    ]);
  });

  it("maps GitHub failures without exposing tokens or private keys", async () => {
    const values = new Map(baseValues);
    values.set("GITHUB_APP_ID", "123");
    values.set("GITHUB_APP_PRIVATE_KEY", await pemPrivateKey());
    const fetchMock = vi
      .fn<typeof fetch>()
      .mockResolvedValue(new Response("not-json", { status: 401 }));
    vi.stubGlobal("fetch", fetchMock);
    const app = await Effect.runPromise(
      Effect.gen(function* () {
        return yield* GitHubApp;
      }).pipe(Effect.provide(service(values))),
    );

    const result = await Effect.runPromise(
      Effect.either(app.createPullRequest(createInput)),
    );
    expect(Either.isLeft(result)).toBe(true);
    if (Either.isLeft(result)) {
      expect(result.left).toBeInstanceOf(GitHubAppApiError);
      expect(result.left.message).not.toContain("installation-secret");
      expect(result.left.message).not.toContain("BEGIN PRIVATE KEY");
    }
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });
});
